from db import supabase
import hashlib

def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

# ---------------- SIGNUP ----------------
def signup(username, password):
    # Check if username exists
    res = supabase.table("users").select("*").eq("username", username).execute()
    if res.data:
        return False

    # Insert new user (UUID will be generated by DB)
    supabase.table("users").insert({
        "username": username,
        "password_hash": hash_password(password),
        "games_played": 0,
        "wins": 0,
        "best_score": 0
    }).execute()
    return True

# ---------------- LOGIN ----------------
def login(username, password):
    res = supabase.table("users") \
        .select("*") \
        .eq("username", username) \
        .eq("password_hash", hash_password(password)) \
        .execute()
    if res.data:
        return res.data[0]  # return user dict
    return None

# ---------------- UPDATE SCORE ----------------
def update_score(username, won, wrong, difficulty):
    if not won:
        score = 0
    else:
        base_score = max(0, 6 - wrong)

        # ---- Difficulty multipliers ----
        if difficulty == "hard":
            score = base_score * 2
        elif difficulty == "medium":
            score = int(round(base_score * 1.5))
        else:  # easy
            score = base_score

    # ---- Fetch current values ----
    user = supabase.table("users") \
        .select("games_played, wins, best_score") \
        .eq("username", username) \
        .execute().data[0]

    supabase.table("users").update({
        "games_played": user["games_played"] + 1,
        "wins": user["wins"] + (1 if won else 0),
        "best_score": max(user["best_score"], score)
    }).eq("username", username).execute()

# ---------------- USER STATS ----------------
def get_user_stats(username):
    res = supabase.table("users").select("*").eq("username", username).execute()
    if res.data:
        user = res.data[0]
        return {
            "games_played": user["games_played"],
            "wins": user["wins"],
            "best_score": user["best_score"]
        }
    return {"games_played": 0, "wins": 0, "best_score": 0}

# ---------------- LEADERBOARD ----------------
def get_leaderboard():
    res = supabase.table("users") \
        .select(
        "username, best_score, wins, games_played"
    ) \
        .order("best_score", desc=True) \
        .limit(10) \
        .execute()
    return res.data
